---
title: "Relatório Estatística Experimental"
author: 
  - "Guilherme Fernandes - 3398"
  - "Júlia Letícia - 3732"
  - "Victor Hugo - 3510"
date: "03/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
source("../funcoes.R")
```

# Base de dados

```{r, include=FALSE, echo=FALSE}
source("../leituraBase.R")
```

```{r, echo=FALSE, fig.align='center'}
base %>% head() %>% knitr::kable()
```


# Análise Geral

## Por Formato de Ensino

```{r, echo=FALSE}
descritivaContinua(
  df = base, 
  variaveis = c("numero_acertos", "idade", "duracao"),
  grupo = "formato_ensino"
) %>% knitr::kable()

descritivaCategorica(
  df = base,
  variaveis = c("sexo", "ano_ingresso", "tratamento", "curso"),
  grupo = "formato_ensino"
) %>% knitr::kable()
```

```{r, echo=FALSE, fig.align='center'}
boxplot(
  df = base,
  Y = "numero_acertos",
  X = "formato_ensino",
  Title = "Número de Acertos por Formato de Ensino",
  labelX = "Número de Acertos",
  labelY = "Formato de Ensino"
)
```

```{r, echo=FALSE}
Anova(base, "numero_acertos ~ formato_ensino", c("Formato do Ensino"))[[2]] %>% knitr::kable()
```


## Por Tratamento

```{r, echo=FALSE}
descritivaContinua(
  df = base, 
  variaveis = c("numero_acertos", "idade", "duracao"),
  grupo = "tratamento"
) %>% knitr::kable()


descritivaCategorica(
  df = base,
  variaveis = c("sexo", "ano_ingresso", "formato_ensino", "curso"),
  grupo = "tratamento"
) %>% knitr::kable()
```

```{r, echo=FALSE}
boxplot(
  df = base,
  Y = "numero_acertos",
  X = "tratamento",
  Title = "Número de Acertos por Tratamento",
  labelX = "Número de Acertos",
  labelY = "Tratamento"
)
```

```{r, echo=FALSE}
Anova(base, "numero_acertos ~ tratamento", c("Tratamento"))[[2]] %>% knitr::kable()
```

## Iteração

```{r, echo=FALSE}
descritivaContinua(
  df = base, 
  variaveis = c("numero_acertos", "idade", "duracao"),
  grupo = c("formato_ensino", "tratamento")
) %>% knitr::kable()


descritivaCategorica(
  df = base,
  variaveis = c("sexo", "ano_ingresso", "curso"),
  grupo = c("tratamento", "formato_ensino")
) %>% knitr::kable()
```

```{r, echo=FALSE, fig.align='center'}
boxplot(
  df = base,
  Y = "numero_acertos",
  X = "formato_ensino",
  grupo = "tratamento",
  Title = "Número de Acertos por Formato de Ensino",
  labelX = "Número de Acertos",
  labelY = "Formato de Ensino",
  legend = "Tratamento"
)
```

```{r, echo=FALSE}
Anova(base, "numero_acertos ~ formato_ensino * tratamento", c("Formato do Ensino", "Tratamento", "Formato do Ensino : Tratamento"))[[2]] %>% knitr::kable()
```

```{r, echo=FALSE}
# TukeyHSD(Anova(base, "numero_acertos ~ formato_ensino * tratamento", c("Formato do Ensino", "Tratamento", "Formato do Ensino : Tratamento"))[[1]])$`formato_ensino:tratamento`
```

```{r, echo=FALSE}
TukeyHSD(Anova(base, "numero_acertos ~ formato_ensino * tratamento", c("Formato do Ensino", "Tratamento", "Formato do Ensino : Tratamento"))[[1]])$`tratamento`
```

# Análise CDC



# Análise Matemática

## Por Formato de Ensino

```{r, echo=FALSE}
descritivaContinua(
  df = baseMAT, 
  variaveis = c("numero_acertos", "idade", "duracao"),
  grupo = "formato_ensino"
) %>% knitr::kable()
```

```{r, echo=FALSE, fig.align='center'}
boxplot(
  df = baseMAT,
  Y = "numero_acertos",
  X = "formato_ensino",
  Title = "Número de Acertos por Formato de Ensino",
  labelX = "Número de Acertos",
  labelY = "Formato de Ensino"
)
```

```{r, echo=FALSE}
Anova(baseMAT, "numero_acertos ~ formato_ensino", c("Formato do Ensino"))[[2]] %>% knitr::kable()
```


## Por Tratamento

```{r, echo=FALSE}
descritivaContinua(
  df = baseMAT, 
  variaveis = c("numero_acertos", "idade", "duracao"),
  grupo = "tratamento"
) %>% knitr::kable()
```

```{r, echo=FALSE}
boxplot(
  df = baseMAT,
  Y = "numero_acertos",
  X = "tratamento",
  Title = "Número de Acertos por Tratamento",
  labelX = "Número de Acertos",
  labelY = "Tratamento"
)
```


```{r, echo=FALSE}
Anova(baseMAT, "numero_acertos ~ tratamento", c("Tratamento"))[[2]] %>% knitr::kable()
```

## Iteração

```{r, echo=FALSE}
descritivaContinua(
  df = baseMAT, 
  variaveis = c("numero_acertos", "idade", "duracao"),
  grupo = c("formato_ensino", "tratamento")
) %>% knitr::kable()
```

```{r, echo=FALSE, fig.align='center'}
boxplot(
  df = baseMAT,
  Y = "numero_acertos",
  X = "formato_ensino",
  grupo = "tratamento",
  Title = "Número de Acertos por Formato de Ensino",
  labelX = "Número de Acertos",
  labelY = "Formato de Ensino",
  legend = "Tratamento"
)
```

```{r, echo=FALSE}
Anova(baseMAT, "numero_acertos ~ formato_ensino * tratamento", c("Formato do Ensino", "Tratamento", "Formato do Ensino : Tratamento"))[[2]] %>% knitr::kable()
```

```{r, echo=FALSE}
TukeyHSD(Anova(baseMAT, "numero_acertos ~ formato_ensino * tratamento", c("Formato do Ensino", "Tratamento", "Formato do Ensino : Tratamento"))[[1]])$`tratamento`
```

